# .github/workflows/ci.yml

name: Node.js CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Use Node.js 22.x
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Check formatting
        run: pnpm run format:check

      - name: Run linter
        run: pnpm lint

      - name: Install Xvfb (display server)
        run: sudo apt-get update && sudo apt-get install -y xvfb

      - name: Run tests with virtual display
        run: xvfb-run pnpm test
